source "http://rubygems.org"

gem "rails", "3.0.10"
gem 'mysql'
gem 'authlogic', "3.0.2"

gem "mime-types"
gem "rack"
gem "paperclip"
gem "uploader", :path => '../../'

if RUBY_VERSION < '1.9'
  gem "ruby-debug"
end

group :test, :development do
  gem "rspec-rails", ">=2.4.0"
  gem "cucumber-rails"
end

group :test do
  gem "capybara", ">= 0.3.9"
  gem "shoulda"
  gem "factory_girl"
  gem "cucumber"
  gem "rcov"
  gem "rspec", ">=2.4.0"
  gem "database_cleaner"
  gem "spork"
  gem "launchy"
end
